---
- name: Configure nginx web server
  hosts: webservers
  tasks:
  - name: Install nginx
    apt:
      name: nginx=1.24*
      state: present
  - name: Start nginx service
    service:
      name: nginx
      state: started